---
version: '3.2'
services:
  face-recognition:
    image: dstilab/face-recognition:0.1
    build:
      context: .
    environment:
      SURROUND_POSTGRES_USER: postgres
      SURROUND_POSTGRES_PASSWORD: postgres
      SURROUND_POSTGRES_HOST: postgres
      SURROUND_POSTGRES_PORT: "5432"
    ports:
      - 8888:8888
      - 8889:8889
    networks:
      - stack
    devices:
      - /dev/video0:/dev/video0
    entrypoint: python3 -m face-recognition
    command: server -w

  # PostgreSQL RDBMS
  postgres:
    image: postgres:9.5-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=face_recognition
      - TZ=UTC
      - PGTZ=UTC
    volumes:
      - ./resources/db/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - stack
    restart: always

volumes:
  postgres-data:
    driver: local

networks:
  stack:
    driver: bridge
